<h2>
    G&auml;stebucheintrag 
    <?php if ($this->entry->getId() == 0): ?>
        hinterlassen
    <?php else: ?>
        bearbeiten
    <?php endif; ?>
</h2>
<form class="form-horizontal" method="post">
    <input type="hidden" name="id" value="<?php echo $this->entry->getId(); ?>" />
    <div class="control-group">
        <label class="control-label" for="author">Autor:</label>
        <div class="controls">
            <input class="required" type="text" id="author" name="author" value="<?php echo $this->entry->getAuthor(); ?>"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="title">Titel:</label>
        <div class="controls">
            <input class="required" type="text" id="title" name="title" value="<?php echo $this->entry->getTitle(); ?>"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="text">Text:</label>
        <div class="controls">
            <textarea class="required" name="text" id="text" rows="3"><?php echo $this->entry->getText(); ?></textarea>
        </div>
    </div>
    <div class="form-actions">
        <button class="btn btn-primary" type="submit"> 
            Senden
        </button>
        <a class="btn" href="<?php echo $this->url(
            array('action' => 'index')
        ); ?>">
            abbrechen    
        </a>
    </div>
</form>