<a href="<?php echo $this->url(
        array('action' => 'edit')
    ); ?>">
    &raquo; Eintragen    
</a>
<?php foreach ($this->entries as $entry): ?>
    <h4>
        <?php echo $entry->getTitle(); ?>
    </h4>
    <blockquote>
        <p>
            <?php echo $entry->getText(); ?>
        </p>
        <small><?php echo $entry->getAuthor(); ?> / <?php echo $this->dateFormater($entry->getDate()); ?></small>
    </blockquote>
    <div class="entry-footer">
        <div class="btn-group">
            <a class="btn-danger btn delete" href="<?php echo $this->url(
                    array('action' => 'delete'
                        , 'id' => $entry->getId()
                    ), true
            ); ?>">
                <i class="icon-trash icon-white"></i>
            </a>
            <a class="btn" href="<?php echo $this->url(
                    array('action' => 'edit'
                        , 'id' => $entry->getId()
                    ), true
            ); ?>">
                Edit
            </a>
        </div>
    </div>
<?php endforeach; ?>
