<h1>Willkommen</h1>
<p>Das ist eine Test und &Uuml;bungsseite von Basti und Rico.</p>

<div class="span5 offset2">
    <h3>BootstrapMagic Inc.</h3>
    <p>Dies ist nur ein kleiner Test zu den Funktionen von Bootstrap.</p>
</div>
<div class="span2 offset5">
    <h3>BootstrapMagic Inc. 2</h3>
    <p>Dies ist nur ein kleiner Test zu den Funktionen von Bootstrap.</p>
</div>
<div class="span10">
    <h3>BootstrapMagic Inc. 3</h3>
    <p>Dies ist nur ein kleiner Test zu den Funktionen von Bootstrap.</p>
</div>
<div class="span4 offset2">
    <h3>BootstrapMagic Inc. 4</h3>
    <p>Dies ist nur ein kleiner Test zu den Funktionen von Bootstrap.</p>
</div>