<div class="row">
    <div class="col-8">
        <h1>Willkommen</h1>

        <p>Das ist eine Test und &Uuml;bungsseite von Rico Schulz.</p>

        <p>Die gesamte Seite wurde mit mit einem eiegenen Freamwork entwickelt. Das Framework ich stehts ein wenig an
            das
            Zend Freamwork angelehnt, versucht aber trotzdem sein eigenen weg zu gehen.</p>
    </div>
    <div class="col-4">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('last_entries'); ?></h3>
            </div>
            <?php foreach ($this->entries as $key => $entry): ?>
                <?php if ($key > 0): ?>
                    <hr>
                <?php endif; ?>
                <h4><?php echo $entry->getTitle(); ?></h4>
                <blockquote>
                    <p><?php echo $entry->getText(); ?></p>
                    <small><?php echo $entry->getUser()->getUsername(); ?>
                        / <?php echo $this->dateFormater($entry->getDate()); ?></small>
                </blockquote>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<form>
    <label for="socketTest">Socket Test</label>
    <input id="socketTest" name="socketTest" type="text"/>

    <div id="socketTestResponse"></div>
</form>
