<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h3>
                    Eintrag l&ouml;schen
                </h3>
            </div>
            <div class="modal-body">
                <p>Eintrag wirklich l&ouml;schen?</p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
                    Ne, lieber doch nicht...
                </button>
                <button class="btn btn-danger">
                    Wirklich l&ouml;schen!
                </button>
            </div>
        </div>
    </div>
</div>