<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3><?php echo $this->translate('delete_modal_title'); ?></h3>
            </div>
            <div class="modal-body">
                <p><?php echo $this->translate('delete_modal_text'); ?></p>
            </div>
            <div class="modal-footer">
                <button class="btn btn-default" data-dismiss="modal" aria-hidden="true">
                    <?php echo $this->translate('abort'); ?>
                </button>
                <button class="btn btn-danger">
                    <?php echo $this->translate('delete'); ?>ss
                </button>
            </div>
        </div>
    </div>
</div>