<div class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Eintrag löschen</h3>
    </div>
    <div class="modal-body">
        <p>Eintrag wirklich löschen?</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn">Ne, lieber doch nicht...</a>
        <a href="#" class="btn btn-danger">Wirklich l&ouml;schen!</a>
    </div>
</div>