<div class="form-group<?php echo ($this->element->hasError() ? ' has-error' : ''); ?>">
    <label class="col-lg-2 control-label" for="<?php echo $this->element->getName() ?>"><?php echo $this->translate($this->element->getLabel()) . ($this->element->isRequired() ? '*' : ''); ?></label>
    <div class="<?php echo $this->element->getSize(); ?>">
        <input
            class="form-control<?php echo ($this->element->isRequired() ? ' required' : ''); ?>"
            <?php echo ($this->element->getPlaceholder() ? ' placeholder="' . $this->translate($this->element->getPlaceholder()) . '"' : ''); ?>
            type="<?php echo $this->element->getType(); ?>"
            id="<?php echo $this->element->getName(); ?>"
            name="<?php echo $this->element->getName(); ?>"
            value="<?php echo $this->element->getValue(); ?>"
            <?php echo ($this->element->isRequired() ? ' required' : ''); ?> />
        <?php if ($this->element->hasError()): ?>
            <span class="help-inline"><?php echo $this->translate($this->element->getErrorText()); ?></span>
        <?php endif; ?>
    </div>
</div>