<div class="form-group">
    <label class="col-2 control-label"
           for="<?php echo $this->element->getName() ?>"><?php echo $this->translate($this->element->getLabel()) . ($this->element->isRequired() ? '*' : ''); ?></label>

    <div class="col-4">
        <select class="form-control" name="<?php echo $this->element->getName() ?>"
                id="<?php echo $this->element->getName() ?>">
            <?php foreach ($this->element->getOptions() as $option): ?>
                <option value="<?php echo $option->getValue(); ?>"
                    <?php echo($option->isSelected() ? 'selected="selected"' : ''); ?>>
                    <?php echo $this->translate($option->getLabel()); ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>