<form action="<?php echo $this->form->getAction(); ?>" class="form-horizontal" method="post">
    <?php if ($this->form->hasActionBar()): ?>
        <?php echo $this->form->getDisplayGroup('actions_bottom')->render(); ?>
    <?php endif; ?>

    <hr>

    <!-- default inputs -->
    <?php echo $this->form->getDisplayGroup(RBMVC\Core\Utilities\Form\DisplayGroup::DEFAULT_ELEMENTS)->render(); ?>
    <!-- end default inputs -->

    <?php if ($this->form->hasDisplayGroup(RBMVC\Core\Utilities\Form\DisplayGroup::HIDDEN_ELEMENTS)): ?>
        <!-- hidden inputs -->
        <?php echo $this->form->getDisplayGroup(RBMVC\Core\Utilities\Form\DisplayGroup::HIDDEN_ELEMENTS)->render(); ?>
        <!-- end hidden inputs -->
    <?php endif; ?>

    <hr>

    <?php if ($this->form->hasActionBar()): ?>
        <?php echo $this->form->getDisplayGroup('actions_bottom')->render(); ?>
    <?php endif; ?>
</form>

<?php /*
    <button type="submit" value="saven_return" class="btn btn-success">
        <?php echo $this->translate('save_and_return'); ?>
    </button>

 */
?>