<!DOCTYPE html>
<html lang="de">
    <head>
        <script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
        <script data-main="/template/js/<?php echo $this->controller; ?>.js" src="/template/js/lib/require-jquery.js"></script>
        <link href="/template/css/bootstrap.css" rel="stylesheet"/>
        <link href="/template/css/bootstrap-responsive.css" rel="stylesheet"/>
        
    </head>
    <body>
        <div class="container">
            <div class="header">
                <div class="row">
                    <div class="span12">
                        <div class="navbar navbar-inverse">
                            <div class="navbar-inner">
                                <ul class="nav">
                                    <li>
                                        <a href="<?php echo $this->url(
                                                array('controller' => 'index'
                                                    , 'action' => 'index'
                                                )
                                        ); ?>">
                                            Start
                                        </a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->url(
                                                array('controller' => 'entry'
                                                    , 'action' => 'index'
                                                )
                                          ); ?>">
                                            G&auml;stebuch
                                        </a>
                                    </li>
                                </ul>
                            </div>  
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="content span12">
                   <?php echo $this->content; ?>
               </div>
            </div>
            <div class="row">
                <div class="footer span12 text-center">
                   <p>POWERT BY Basti/Rico</p>
                </div> 
            </div>
        </div>
    </body>
</html>