<!DOCTYPE html>
<html lang="de">
    <head>
        <script data-main="/js/<?php echo $this->controller; ?>.js" src="/js/lib/require-jquery.js"></script>
        <?php echo $this->addStyle('bootstrap.min.css'); ?>
    </head>
    <body>
        <?php echo $this->partial('nav.phtml'); ?>
        <br />
        <div class="container">
            <div class="row">
                <div class="span12">
                   <?php echo $this->content; ?>
               </div>
            </div>
        </div>
        
        <br />
        
        <footer class="footer">
            <p class="text-center">POWERT BY Basti/Rico</p>
        </footer>
        
        <?php echo $this->partial('deleteModal.phtml'); ?>
    </body>
</html>