<div class="btn-group">
    <a class="btn btn-primary" href="<?php echo $this->url(array('action' => 'edit')); ?>">
        <i class="icon-plus"></i> <?php echo $this->translate('add'); ?>
    </a>
</div>

<hr>

<table class="table table-striped table-hover table-condensed">
    <thead>
        <tr>
            <th><?php echo $this->translate('id'); ?></th>
            <th><?php echo $this->translate('username'); ?></th>
            <th><?php echo $this->translate('email'); ?></th>
            <th><?php echo $this->translate('is_active'); ?></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <td><?php echo $user->getId(); ?></td>
            <td><?php echo $user->getUsername(); ?></td>
            <td><?php echo $user->getEmail(); ?></td>
            <td class="text-center <?php echo ($user->isActive() ? 'text-success' : 'text-danger'); ?>">
                <i class="icon-2x <?php echo ($user->isActive() ? 'icon-ok-sign' : 'icon-remove-sign'); ?>"></i>
            </td>
            <td>
                <div class="btn-group pull-right">
                    <a class="btn-danger btn delete" data-toggle="modal" href="<?php echo $this->url(
                        array('action' => 'delete'
                              , 'id' => $user->getId()
                        ), true
                    ); ?>">
                        <i class="icon-trash"></i>
                    </a>
                    <a class="btn btn-default" href="<?php echo $this->url(
                        array('action' => 'edit'
                              , 'id' => $user->getId()
                        ), true
                    ); ?>">
                        <i class="icon-edit"></i>
                        <?php echo $this->translate('edit'); ?>
                    </a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>