<?php if ($this->hasAccess($this->url(array('action' => 'add')))): ?>
    <div class="btn-group">
        <?php echo $this->button('add'); ?>
    </div>

    <hr>
<?php endif; ?>

    <table class="table table-striped table-hover table-condensed">
        <thead>
        <tr>
            <th><?php echo $this->translate('id'); ?></th>
            <th><?php echo $this->translate('username'); ?></th>
            <th><?php echo $this->translate('email'); ?></th>
            <th><?php echo $this->translate('is_active'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->users as $user): ?>
            <?php /** @var \Application\Lib\Model\User $user */ ?>
            <tr>
                <td><?php echo $user->getId(); ?></td>
                <td><?php echo $user->getUsername(); ?></td>
                <td><?php echo $user->getEmail(); ?></td>
                <td class="text-center <?php echo($user->isActive() ? 'text-success' : 'text-danger'); ?>">
                    <i class="icon-2x <?php echo($user->isActive() ? 'icon-ok-sign' : 'icon-remove-sign'); ?>"></i>
                </td>
                <td>
                    <div class="btn-group pull-right">
                        <?php echo $this->button('edit', $user->getId()); ?>
                        <?php echo $this->button('delete', $user->getId()); ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

<?php echo $this->pagination(); ?>