<?php if ($this->hasAccess($this->url(array('action' => 'add')))): ?>
    <div class="btn-group">
        <?php echo $this->button('add'); ?>
    </div>

    <hr>
<?php endif; ?>

    <table class="table table-striped table-hover table-condensed">
        <thead>
        <tr>
            <th><?php echo $this->translate('id'); ?></th>
            <th><?php echo $this->translate('code'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->languages as $language): ?>
            <?php /** @var \Application\Lib\Model\Language $language */ ?>
            <tr>
                <td><?php echo $language->getId(); ?></td>
                <td><?php echo $language->getCode(); ?></td>
                <td>
                    <div class="btn-group pull-right">
                        <?php echo $this->button('edit', $language->getId()); ?>
                        <?php echo $this->button('delete', $language->getId()); ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

<?php echo $this->pagination(); ?>