<div class="btn-group">
    <a class="btn btn-primary" href="<?php echo $this->url(array('action' => 'edit')); ?>">
        <i class="icon-plus"></i> <?php echo $this->translate('add'); ?>
    </a>
    <a class="btn btn-default" href="<?php echo $this->url(array('action' => 'scan')); ?>">
        <i class="icon-cogs"></i> <?php echo $this->translate('scan_grants'); ?>
    </a>
</div>

<hr>

<table class="table table-striped table-hover table-condensed">
    <thead>
    <tr>
        <th><?php echo $this->translate('id'); ?></th>
        <th><?php echo $this->translate('definition'); ?></th>
        <th><?php echo $this->translate('type'); ?></th>
        <th><?php echo $this->translate('is_active'); ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->grants as $grant): ?>
        <tr>
            <td><?php echo $grant->getId(); ?></td>
            <td><?php echo $grant->getDefinition(); ?></td>
            <td><?php echo $this->translate('grant_type_' . $grant->getType()); ?></td>
            <td class="text-center <?php echo ($grant->isActive() ? 'text-success' : 'text-danger'); ?>">
                <i class="icon-2x <?php echo ($grant->isActive() ? 'icon-ok-sign' : 'icon-remove-sign'); ?>"></i>
            </td>
            <td>
                <div class="btn-group pull-right">
                    <a class="btn-danger btn delete" data-toggle="modal" href="<?php echo $this->url(
                        array('action' => 'delete'
                              , 'id' => $grant->getId()
                        ), true
                    ); ?>">
                        <i class="icon-trash"></i>
                    </a>
                    <a class="btn btn-default" href="<?php echo $this->url(
                        array('action' => 'edit'
                              , 'id' => $grant->getId()
                        ), true
                    ); ?>">
                        <i class="icon-edit"></i>
                        <?php echo $this->translate('edit'); ?>
                    </a>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>