<?php if ($this->hasAccess($this->url(array('action' => 'add')))
    || $this->hasAccess($this->url(array('action' => 'scan')))
): ?>
    <div class="btn-group">
        <?php echo $this->button('add'); ?>
        <?php echo $this->button(array(
                                      'url'   => $this->url(array('action' => 'scan')),
                                      'icon'  => 'icon-cogs',
                                      'class' => 'btn-default',
                                      'label' => 'scan_grants',
                                 )); ?>
    </div>

    <hr>
<?php endif; ?>

    <table class="table table-striped table-hover table-condensed">
        <thead>
        <tr>
            <th><?php echo $this->translate('id'); ?></th>
            <th><?php echo $this->translate('definition'); ?></th>
            <th><?php echo $this->translate('type'); ?></th>
            <th><?php echo $this->translate('is_active'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->grants as $grant): ?>
            <tr>
                <td><?php echo $grant->getId(); ?></td>
                <td><?php echo $grant->getDefinition(); ?></td>
                <td><?php echo $this->translate('grant_type_' . $grant->getType()); ?></td>
                <td class="text-center <?php echo($grant->isActive() ? 'text-success' : 'text-danger'); ?>">
                    <i class="icon-2x <?php echo($grant->isActive() ? 'icon-ok-sign' : 'icon-remove-sign'); ?>"></i>
                </td>
                <td>
                    <div class="btn-group pull-right">
                        <?php echo $this->button('edit', $grant->getId()); ?>
                        <?php echo $this->button('delete', $grant->getId()); ?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

<?php echo $this->pagination(); ?>