<div class="btn-group">
    <?php echo $this->button('add'); ?>
</div>

<hr>

<table class="table table-striped table-hover table-condensed">
    <thead>
    <tr>
        <th><?php echo $this->translate('id'); ?></th>
        <th><?php echo $this->translate('name'); ?></th>
        <th><?php echo $this->translate('description'); ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->userGroups as $group): ?>
        <tr>
            <td><?php echo $group->getId(); ?></td>
            <td><?php echo $group->getName(); ?></td>
            <td><?php echo $group->getDescription(); ?></td>
            <td>
                <div class="btn-group pull-right">
                    <a class="btn-danger btn delete" data-toggle="modal" href="<?php echo $this->url(
                        array('action' => 'delete'
                              , 'id'   => $group->getId()
                        ), true
                    ); ?>">
                        <i class="icon-trash"></i>
                    </a>
                    <?php echo $this->button('edit', $group->getId()); ?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>